services:

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - users_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  web:
    build:
      context: ..
      dockerfile: ./docker/dev.Dockerfile
    environment:
      - DOCKER_BUILDKIT=1
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
      #- DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host=0.0.0.0"
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - ../.env

volumes:
  users_data:
